// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04SFfElHAeGmTSwfdz0HEPkQxOW-U4kY',
    appId: '1:641301277916:web:ea8ffd50a91274a827d819',
    messagingSenderId: '641301277916',
    projectId: 'abs-center-control',
    authDomain: 'abs-center-control.firebaseapp.com',
    storageBucket: 'abs-center-control.appspot.com',
    measurementId: 'G-RCHLWTZ88Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQ6UnonF85T5BKagxtXwePPeRlN42_Cs',
    appId: '1:641301277916:android:56f240401404216227d819',
    messagingSenderId: '641301277916',
    projectId: 'abs-center-control',
    storageBucket: 'abs-center-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE49ANlkYA8nyDMG2FDviI80B_XeCjAV4',
    appId: '1:641301277916:ios:d58ed4f3ba13d14d27d819',
    messagingSenderId: '641301277916',
    projectId: 'abs-center-control',
    storageBucket: 'abs-center-control.appspot.com',
    iosBundleId: 'com.espace.btsManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE49ANlkYA8nyDMG2FDviI80B_XeCjAV4',
    appId: '1:641301277916:ios:d58ed4f3ba13d14d27d819',
    messagingSenderId: '641301277916',
    projectId: 'abs-center-control',
    storageBucket: 'abs-center-control.appspot.com',
    iosBundleId: 'com.espace.btsManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB04SFfElHAeGmTSwfdz0HEPkQxOW-U4kY',
    appId: '1:641301277916:web:18f7afc435df0b8f27d819',
    messagingSenderId: '641301277916',
    projectId: 'abs-center-control',
    authDomain: 'abs-center-control.firebaseapp.com',
    storageBucket: 'abs-center-control.appspot.com',
    measurementId: 'G-X4YY835W5L',
  );

}